name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jao-oliveira
          svg_out_path: dist/github-contribution-grid-snake.svg
      

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          <picture>
            <source media="(prefers-color-scheme: dark)" srcset="github-snake-dark.svg" />
            <source media="(prefers-color-scheme: light)" srcset="github-snake.svg" />
            <img alt="github-snake" src="github-snake.svg" />
          </picture>

